DROP FUNCTION IF EXISTS getLabel ;
CREATE FUNCTION getLabel () 
 RETURNS TABLE (
 query_id INTEGER,
 query_label VARCHAR(100) 
) 
AS $$
BEGIN
 RETURN QUERY SELECT
 nom
 FROM
 TEST10 ;
END; $$ 
LANGUAGE 'plpgsql';
